config/routes.rb
Rails.application.routes.draw do
  root to: "rooms#lobby"

  resource :user

  resources :rooms do
    resources :messages
    resources :members, controller: :room_members
  end
end

app/models/filter_chain.rb
require 'filters'

class FilterChain
  attr_reader :message, :filters

  def initialize(message)
    @message = message
    @filters = []
  end

  def add_random(num = 5)
    @filters += Filters.constants.shuffle.take(num)
    self
  end

  def process
    puts "PROCESSING message #{message.inspect}"

    result = message.text
    filters.each do |f|
      puts "STARTING filter #{f} for message #{message.inspect}"

      publish({
        type: 'before_filter',
        message: result,
        filter: f
      })

      filter = Filters.const_get(f).new
      result = filter.apply(result)

      puts "FINISHED filter #{f} for message #{message.inspect}"
    end

    publish({
      type: 'after_process',
      message: result
    })

    puts "PROCESSING COMPLETE message #{message.inspect}"
  end

  handle_asynchronously :process

  private

  def publish(payload = {})
    final_payload = payload.merge({ id: SecureRandom.uuid, message_id: message.id, sender_id: message.sender.id })
    client.publish(channel: message.room.id, message: final_payload) do |r|
      puts "published message #{r.inspect}"
    end
    sleep 1
  end

  def client
    @client ||= Pubnub.new(:subscribe_key => "demo", :publish_key => "demo")
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :sender, :text, :room

  validates :text, presence: true

  def id
    @id ||= SecureRandom.uuid
  end

  def submit
    MessagePublisher.new(self).publish
  end
end

app/models/message_publisher.rb
class MessagePublisher

  attr_reader :message

  delegate :room, :sender, to: :message

  def initialize(message)
    @message = message
  end

  def publish
    translations = translate_for_room
    _publish({
      message_id: message.id,
      sender_name: sender.name,
      sender_id: sender.id,
      source_language: sender.language,
      original_text: message.text,
      message: translations
    })
  end

  def translate_for_room
    room.member_languages.each_with_object({}) do |l, memo|
      memo[l] = Translator.new(sender.language, l).translate(message.text)
    end
  end

  private

  def _publish(payload)
    client.publish(channel: room.id, message: payload) do |r|
      puts "published message #{r.inspect}"
    end
  end

  def client
    @client ||= Pubnub.new(:subscribe_key => "sub-c-758a8ca2-824f-11e4-8e7a-02ee2ddab7fe", :publish_key => "pub-c-61366627-4469-4726-8061-4d1f3ce606a9")
  end
end

app/models/multillect_translator.rb
require 'faraday_middleware'


TWO_TO_THREE_CODES={ ru: 'rus', en: 'eng', ar: 'ara', fr: 'fra', de: 'deu', es: 'spa', tr: 'tur', uk: 'ukr' }

class MultillectTranslator

  def translate(from_lang, to_lang, input)

    from_lang_three = two_code_to_three_code from_lang
    to_lang_three = two_code_to_three_code to_lang

    param_hash = {
      method: 'translate/api/translate',
      sig: 'ed6c2682a2eeb57989d9ce1fc8732c93',
      # sig: '9c7dd4236b1d38f2b8151a6fe139708d', # sarah's multilect key for emergency use
      from: from_lang_three,
      to: to_lang_three,
      text: input
    }

    conn = Faraday.new "http://api.multillect.com" do |faraday|
      faraday.response :json
      faraday.adapter Faraday.default_adapter
    end

    response = conn.get("/translate/json/1.0/36", param_hash)
    raise ("Error: #{response.body}") if response.status != 200

    response.body['result']['translated'].strip
  end

  def two_code_to_three_code(two_code)
    TWO_TO_THREE_CODES[two_code.to_sym] || raise("#{two_code} is an unsupported language.")
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_presences
  has_many :active_room_presences, -> { merge(RoomPresence.active) }, class_name: 'RoomPresence'
  has_many :members, through: :active_room_presences

  def build_message(opts = {})
    Message.new opts.merge(room: self)
  end

  def member_languages
    members.map(&:language).uniq
  end
end

app/models/room_presence.rb
class RoomPresence < ActiveRecord::Base
  TIMEOUT = 10.seconds
  belongs_to :room
  belongs_to :member, class_name: 'User'

  scope :active, -> { where("room_presences.updated_at > ?", TIMEOUT.ago) }
end

app/models/translator.rb
require 'filters'

class Translator
  attr_reader :from, :to

  def initialize(from, to)
    @from = from
    @to = to
  end

  def translate(input)
    if from == to
      input.start_with?("###") ? Filters::ObfuscateUnicode.new.apply(input[3..-1]).strip : input
    else
      output = MultillectTranslator.new.translate(from, to, input)
      input.start_with?("###") ? Filters::ObfuscateUnicode.new.apply(output[3..-1]).strip : output
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_default_language

  private

  def set_default_language
    self.language = 'en' unless self.language
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :allow_iframe_requests

  private

  def current_user
    @current_user ||= User.find_by id: cookies.permanent.signed[:user_id]
    @current_user ||= User.create!
    cookies.permanent.signed[:user_id] = @current_user.id
    @current_user
  end

  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @room = Room.find params[:room_id]
    @message = @room.build_message(default_create_params.merge(create_params))
    if @message.valid?
      @message.submit
      @message = @room.build_message default_create_params
      render 'messages/create'
    else
      render 'messages/create'
    end
  end

  private

  def default_create_params
    { sender: current_user }
  end

  def create_params
    params.require(:message).permit(:text)
  end
end

app/controllers/room_members_controller.rb
class RoomMembersController < ApplicationController
  def index
    @room = Room.find params[:room_id]
    @room.room_presences.find_or_create_by(member: current_user).touch
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    redirect_to Room.create!
  end

  def lobby
    redirect_to Room.first
  end

  def show
    @room = Room.find(params[:id])
    @room.room_presences.find_or_create_by(member: current_user).touch
    @message = @room.build_message(sender: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    current_user.update update_params
    render 'update'
  end

  private

  def update_params
    params.require(:user).permit(:name, :language)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def language_options
    [
      ['English', 'en'],
      ['Spanish', 'es'],
      ['French', 'fr'],
      ['Russian', 'ru'],
      ['Ukrainian', 'uk'],
      ['German', 'de'],
      ['Arabic', 'ar'],
      ['Turkish', 'tr']
    ]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jaunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="main">
    <%= render 'shared/main_header' %>
  </header>

  <%= yield %>

  <%= yield :javascript %>

  <footer>
    <p>Built with love for <a href="https://koding.com/Hackathon" target=_blank>Koding Global Hackathon</a></p>
    <p>The team: <a href="http://twitter.com/nonrational" target="_blank">@nonrational</a>, <a href="http://twitter.com/samandmoore" target="_blank">@samandmore</a>, <a href="http://twitter.com/jmileham" target="_blank">@jmileham</a>, <a href="http://twitter.com/madysondesigns" target="_blank">@madysondesigns</a></p>
  </footer>
</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for [@room, @message], remote: true do |f| %>
  <%= f.input :text, label: '', placeholder: 'Say something...' %>
  <%= f.button :submit, value: 'Send', 'data-disable-with' => 'Sending...' %>
<% end %>

app/views/messages/create.js.erb
$("#message_create_form form").html($("<%= j render partial: 'form' %>").html());

app/views/room_members/_index.html.erb
<p>People in this room</p>
<ul class="members">
  <% @room.members.each do |m| %>
    <li><%= m.name %><%= current_user == m ? ' (You)' : '' %></li>
  <% end %>
</ul>

app/views/room_members/index.js.erb
$(".room-info").html("<%= j render partial: 'index' %>")

app/views/rooms/show.html.erb
<section class="room-header">
  <div class="user-display">
    <div class="name">
      <%= render 'users/name' %>
    </div>

    <div class="user-language">
      <%= render 'users/language' %>
    </div>
  </div>

  <div class="room-info">
    <%= render 'room_members/index' %>
  </div>
</section>

<section class="messages">
  <div class="scroll">
    <ul id="messages">
    </ul>
  </div>
</section>

<section class="message-input" id="message_create_form">
  <%= render 'messages/form' %>
  <script>
      $(document).ready(function(){
          $('.invite').click(function() {
            $('.invite input').select().focus();
          });
      });
  </script>
  <p class="invite">Invite someone to this room: <input value="http://samandmoore.koding.io<%= room_path %>" /></p>
  <%= link_to "Start a new room", rooms_path, method: :post, class: "new-room" %>
</section>


<%= content_for :javascript do %>
<script src="https://pubnub.a.ssl.fastly.net/pubnub.min.js"></script>
<script>
  (function() {
    WebSocket = PUBNUB.ws;
    var $messages = $('#messages');
    var socket = new WebSocket('wss://pubsub.pubnub.com/pub-c-61366627-4469-4726-8061-4d1f3ce606a9/sub-c-758a8ca2-824f-11e4-8e7a-02ee2ddab7fe/<%= @room.id %>');
    var currentUserId = '<%= current_user.id %>';
    var colors = [
      '#ff00ff',
      '#00ffff',
      '#00ff00',
      '#ffff00',
      '#ff0000',
      '#0000ff',
      '#7920FF',
      '#FD0987',
      '#FF3300',
      '#49D3F2',
      '#D2691E',
      '#CE3977',
      '#33A1C9',
      '#FFDB00',
      '#09A9B2',
      '#8C92AC',
      '#87A96B',
      '#43CD80',
      '#FFA500',
      '#FF82AB'
    ];

    function getColorForSender(data) {
      return colors[parseInt(md5(data.sender_id).substring(0,8),16) % colors.length];
    }

    var tmpl = {
      sender: function(data) {
        var senderInitial = (data.sender_name || '?').charAt(0),
            $senderElement = $('<figure/>').addClass('message-sender'),
            $userIcon = $('<div/>').css('background-color', getColorForSender(data)).text(senderInitial),
            $userName = $('<figcaption>').text(data.sender_name || '?');

        $senderElement.append($userIcon).append($userName);

        return $senderElement;
      },
      messageBody: function(data) {
        return $('<div/>')
          .addClass('message-body')
          .text(data.message[currentLanguage()])
          .attr('title', data.source_language + ' -> ' + data.original_text);
      },
      message: function(data) {
        var $li = $("<li/>").append(this.sender(data)).append(this.messageBody(data));

        if (data.sender_id === currentUserId) {
          $li.addClass('me');
        }

        return $li;
      }
    };

    function currentLanguage() {
      return $('#user_language').val();
    }

    socket.onmessage = function(evt) {
      console.log('message received', evt.data);
      $messages.append(tmpl.message(evt.data));

      var $scroller = $('.messages .scroll');

      $scroller.scrollTop($scroller[0].scrollHeight);
    }

    socket.onclose = function() {
    }

    socket.onerror = function() {
    }

    socket.onopen = function(evt) {
    }

    socket.onsend = function(evt) {
    }

    setInterval(function() {
      $.get('<%= room_members_path(@room) %>')
    }, <%= RoomPresence::TIMEOUT * 500 %>);
  })();

  $(document).on('click', '.room-info p', function() {
      open = $('.members').is(':visible');
      $('.members').slideToggle(!open);
  });

  $('#message_create_form form').on('ajax:success', function() {
    $('#message_text').focus();
  });
</script>
<% end %>

app/views/shared/_main_header.html.erb
<nav>
    <figure>
        <svg viewBox="0 0 179.1 34.4">
            <g>
                <path d="M15.9,22.8c0,2.6-0.3,4.3-0.8,5c-0.5,0.7-1.8,1.1-3.7,1.1c-3.2,0-4.8-1-4.9-3.1c-0.1-0.9-0.1-1.6-0.1-2.2
                    c0-0.6-0.1-1.6-0.2-2.9H0.1L0,23.3c0,4.7,0.7,7.7,2.1,9.1c1.4,1.4,4.5,2.1,9.2,2.1c4.5,0,7.4-0.7,8.9-2.2c1.5-1.4,2.2-4.3,2.2-8.7
                    V0h-6.5V22.8z"/>
                <polygon points="56.8,28.2 52.6,28.2 42.9,0 35.9,0 24.2,34.1 31.1,34.1 31.1,34.1 38.2,34.1 36.2,28.2 32.9,28.2 39.3,8 39.5,8
                    47.7,34.1 54.6,34.1 54.6,34.1 58.8,34.1     "/>
                <path d="M81.1,22.8c0,2.7-0.4,4.3-1.3,5c-0.9,0.7-3,1-6.4,1c-3.3,0-5.5-0.3-6.4-1c-0.9-0.7-1.4-2.3-1.4-4.8V0h-6.5v23.1
                    c0,4.7,0.9,7.7,2.8,9.2c1.9,1.5,5.8,2.2,11.7,2.2c5.6,0,9.4-0.8,11.2-2.3c1.8-1.5,2.7-4.7,2.7-9.4V0h-6.5V22.8z"/>
                <polygon points="114.5,23.3 114.3,23.3 100.6,0 93.7,0 93.7,34.1 100.6,34.1 100.6,10.8 100.7,10.8 114.5,34.1 121.3,34.1 121.3,0
                    114.5,0     "/>
                <polygon points="125.2,5.3 134.8,5.3 134.8,34.1 141.6,34.1 141.6,5.3 151.3,5.3 151.3,0 125.2,0  "/>
                <polygon points="153,0 153,5.3 162.6,5.3 162.6,34.1 169.5,34.1 169.5,5.3 179.1,5.3 179.1,0  "/>
            </g>
        </svg>
    </figure>
</nav>

app/views/shared/_user_header.html.erb
<h1>
  hi, <span class="current_user_name"><%= current_user.name.blank? ? '________' : current_user.name  %></span>
  <%= simple_form_for current_user, remote: true do |f| %>
    <%= f.input_field :name, class: 'hidden' %>
  <% end %>
</h1>

app/views/users/_language.html.erb
<%= simple_form_for current_user, remote: true do |f| %>
  <%= f.input_field :language, collection: language_options, include_blank: false, onchange: "javascript:$(this.form).trigger('submit.rails');" %>
<% end %>

app/views/users/_name.html.erb
<h1>
  Hi, <span class="current-user-name"><%= current_user.name.blank? ? '________' : current_user.name  %></span>
  <%= simple_form_for current_user, remote: true do |f| %>
    <%= f.input_field :name, class: 'hidden' %>
  <% end %>
</h1>

app/views/users/update.js.erb
$(".user-display .name").html("<%= j render partial: 'name' %>");
$(".user_language").html("<%= j render partial: 'language' %>");